default_agent: agentcore_sigma_q
agents:
  agentcore_sigma_q:
    name: agentcore_sigma_q
    language: python
    node_version: '20'
    entrypoint: src/main.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: D:\Github\agent_core_integrations
    aws:
      execution_role: arn:aws:iam::471112810669:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-e45571cd7c
      execution_role_auto_create: false
      account: '471112810669'
      region: us-east-1
      ecr_repository: 471112810669.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-agentcore_sigma_q
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: true
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: agentcore_sigma_q-NR7E2SBiPC
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:471112810669:runtime/agentcore_sigma_q-NR7E2SBiPC
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-agentcore_sigma_q-builder
      execution_role: arn:aws:iam::471112810669:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-e45571cd7c
      source_bucket: bedrock-agentcore-codebuild-sources-471112810669-us-east-1
    memory:
      mode: STM_ONLY
      memory_id: agentcore_sigma_q_mem-8MCsnL7K5W
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:471112810669:memory/agentcore_sigma_q_mem-8MCsnL7K5W
      memory_name: agentcore_sigma_q_mem
      event_expiry_days: 7
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
